export const COMMON_ICONS = {
  add1x: require("@foodstyles/assets/images/add@1x.png"),
  add2x: require("@foodstyles/assets/images/add@2x.png"),
  add3x: require("@foodstyles/assets/images/add@3x.png"),
  close: require("@foodstyles/assets/images/close.png"),
  close2x: require("@foodstyles/assets/images/close@2x.png"),
  close3x: require("@foodstyles/assets/images/close@3x.png"),
  delete: require("@foodstyles/assets/images/delete.png"),
  delete2x: require("@foodstyles/assets/images/delete@2x.png"),
  delete3x: require("@foodstyles/assets/images/delete@3x.png"),
  duplicate: require("@foodstyles/assets/images/duplicate.png"),
  duplicate2x: require("@foodstyles/assets/images/duplicate@2x.png"),
  duplicate3x: require("@foodstyles/assets/images/duplicate@3x.png"),
  logo: require("@foodstyles/assets/images/logo.png"),
  logo2x: require("@foodstyles/assets/images/logo@2x.png"),
  logo3x: require("@foodstyles/assets/images/logo@3x.png"),
  options: require("@foodstyles/assets/images/options.png"),
  options2x: require("@foodstyles/assets/images/options@2x.png"),
  options3x: require("@foodstyles/assets/images/options@3x.png"),
  share: require("@foodstyles/assets/images/share.png"),
  share2x: require("@foodstyles/assets/images/share@2x.png"),
  share3x: require("@foodstyles/assets/images/share@3x.png"),
};
