export const COMMON_ICONS = {
  add1x: require("@foodstyles/assets/images/add1x.png"),
  add2x: require("@foodstyles/assets/images/add2x.png"),
  add3x: require("@foodstyles/assets/images/add3x.png"),
  close: require("@foodstyles/assets/images/close.png"),
  close2x: require("@foodstyles/assets/images/close2x.png"),
  close3x: require("@foodstyles/assets/images/close3x.png"),
  delete: require("@foodstyles/assets/images/delete.png"),
  delete2x: require("@foodstyles/assets/images/delete2x.png"),
  delete3x: require("@foodstyles/assets/images/delete3x.png"),
  duplicate: require("@foodstyles/assets/images/duplicate.png"),
  duplicate2x: require("@foodstyles/assets/images/duplicate2x.png"),
  duplicate3x: require("@foodstyles/assets/images/duplicate3x.png"),
  logo: require("@foodstyles/assets/images/logo.png"),
  logo2x: require("@foodstyles/assets/images/logo2x.png"),
  logo3x: require("@foodstyles/assets/images/logo3x.png"),
  options: require("@foodstyles/assets/images/options.png"),
  options2x: require("@foodstyles/assets/images/options2x.png"),
  options3x: require("@foodstyles/assets/images/options3x.png"),
  share: require("@foodstyles/assets/images/share.png"),
  share2x: require("@foodstyles/assets/images/share2x.png"),
  share3x: require("@foodstyles/assets/images/share3x.png"),
};
